# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(421, 597)
        icon = QIcon()
        icon.addFile(u"icon.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cbABand = QComboBox(self.centralwidget)
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.addItem("")
        self.cbABand.setObjectName(u"cbABand")
        self.cbABand.setGeometry(QRect(60, 110, 141, 31))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(10)
        self.cbABand.setFont(font)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 421, 61))
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 401, 20))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(12)
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(60, 90, 61, 16))
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(11)
        self.label_3.setFont(font3)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(220, 90, 61, 16))
        self.label_4.setFont(font3)
        self.cbBBand = QComboBox(self.centralwidget)
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.addItem("")
        self.cbBBand.setObjectName(u"cbBBand")
        self.cbBBand.setGeometry(QRect(220, 110, 141, 31))
        self.cbBBand.setFont(font)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(90, 160, 61, 16))
        self.label_5.setFont(font3)
        self.cbMultiplier = QComboBox(self.centralwidget)
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.addItem("")
        self.cbMultiplier.setObjectName(u"cbMultiplier")
        self.cbMultiplier.setGeometry(QRect(60, 180, 141, 31))
        self.cbMultiplier.setFont(font)
        self.cbTolerance = QComboBox(self.centralwidget)
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.addItem("")
        self.cbTolerance.setObjectName(u"cbTolerance")
        self.cbTolerance.setGeometry(QRect(220, 180, 141, 31))
        self.cbTolerance.setFont(font)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(220, 160, 61, 16))
        self.label_6.setFont(font3)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(60, 350, 301, 61))
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lblCodedVal = QLabel(self.groupBox)
        self.lblCodedVal.setObjectName(u"lblCodedVal")
        self.lblCodedVal.setGeometry(QRect(10, 22, 281, 31))
        font4 = QFont()
        font4.setFamily(u"Segoe UI")
        font4.setPointSize(14)
        font4.setBold(True)
        font4.setWeight(75)
        self.lblCodedVal.setFont(font4)
        self.lblCodedVal.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(60, 430, 301, 161))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lblToleranceVal = QLabel(self.groupBox_2)
        self.lblToleranceVal.setObjectName(u"lblToleranceVal")
        self.lblToleranceVal.setGeometry(QRect(10, 20, 281, 31))
        self.lblToleranceVal.setFont(font4)
        self.lblToleranceVal.setAlignment(Qt.AlignCenter)
        self.lblMaxTolerance = QLabel(self.groupBox_2)
        self.lblMaxTolerance.setObjectName(u"lblMaxTolerance")
        self.lblMaxTolerance.setGeometry(QRect(10, 80, 281, 21))
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(11)
        font5.setBold(True)
        font5.setWeight(75)
        self.lblMaxTolerance.setFont(font5)
        self.lblMaxTolerance.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 60, 101, 16))
        font6 = QFont()
        font6.setFamily(u"Segoe UI")
        font6.setPointSize(9)
        self.label_7.setFont(font6)
        self.lblMinTolerance = QLabel(self.groupBox_2)
        self.lblMinTolerance.setObjectName(u"lblMinTolerance")
        self.lblMinTolerance.setGeometry(QRect(10, 130, 281, 21))
        self.lblMinTolerance.setFont(font5)
        self.lblMinTolerance.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 110, 101, 16))
        self.label_8.setFont(font6)
        self.btnSolve = QPushButton(self.centralwidget)
        self.btnSolve.setObjectName(u"btnSolve")
        self.btnSolve.setGeometry(QRect(150, 230, 111, 41))
        font7 = QFont()
        font7.setFamily(u"Segoe UI")
        font7.setPointSize(10)
        font7.setBold(True)
        font7.setWeight(75)
        self.btnSolve.setFont(font7)
        self.btnSolve.setCursor(QCursor(Qt.PointingHandCursor))
        self.btnSolve.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(60, 280, 141, 61))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lblMultiplier = QLabel(self.groupBox_3)
        self.lblMultiplier.setObjectName(u"lblMultiplier")
        self.lblMultiplier.setGeometry(QRect(10, 22, 121, 31))
        self.lblMultiplier.setFont(font7)
        self.lblMultiplier.setAlignment(Qt.AlignCenter)
        self.groupBox_4 = QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(220, 280, 141, 61))
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lblTolerance = QLabel(self.groupBox_4)
        self.lblTolerance.setObjectName(u"lblTolerance")
        self.lblTolerance.setGeometry(QRect(10, 22, 121, 31))
        self.lblTolerance.setFont(font7)
        self.lblTolerance.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Carbon Resistors Decoder", None))
        self.cbABand.setItemText(0, QCoreApplication.translate("MainWindow", u"Black", None))
        self.cbABand.setItemText(1, QCoreApplication.translate("MainWindow", u"Brown", None))
        self.cbABand.setItemText(2, QCoreApplication.translate("MainWindow", u"Red", None))
        self.cbABand.setItemText(3, QCoreApplication.translate("MainWindow", u"Orange", None))
        self.cbABand.setItemText(4, QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.cbABand.setItemText(5, QCoreApplication.translate("MainWindow", u"Green", None))
        self.cbABand.setItemText(6, QCoreApplication.translate("MainWindow", u"Blue", None))
        self.cbABand.setItemText(7, QCoreApplication.translate("MainWindow", u"Violet", None))
        self.cbABand.setItemText(8, QCoreApplication.translate("MainWindow", u"Gray", None))
        self.cbABand.setItemText(9, QCoreApplication.translate("MainWindow", u"White", None))

        self.cbABand.setProperty("placeholderText", QCoreApplication.translate("MainWindow", u"Color of the A-Band", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Decoding Carbon Resistors", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"4 - Band", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"A - Band", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"B - Band", None))
        self.cbBBand.setItemText(0, QCoreApplication.translate("MainWindow", u"Black", None))
        self.cbBBand.setItemText(1, QCoreApplication.translate("MainWindow", u"Brown", None))
        self.cbBBand.setItemText(2, QCoreApplication.translate("MainWindow", u"Red", None))
        self.cbBBand.setItemText(3, QCoreApplication.translate("MainWindow", u"Orange", None))
        self.cbBBand.setItemText(4, QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.cbBBand.setItemText(5, QCoreApplication.translate("MainWindow", u"Green", None))
        self.cbBBand.setItemText(6, QCoreApplication.translate("MainWindow", u"Blue", None))
        self.cbBBand.setItemText(7, QCoreApplication.translate("MainWindow", u"Violet", None))
        self.cbBBand.setItemText(8, QCoreApplication.translate("MainWindow", u"Gray", None))
        self.cbBBand.setItemText(9, QCoreApplication.translate("MainWindow", u"White", None))

        self.cbBBand.setProperty("placeholderText", QCoreApplication.translate("MainWindow", u"Color of the B-Band", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"C - Band", None))
        self.cbMultiplier.setItemText(0, QCoreApplication.translate("MainWindow", u"Black", None))
        self.cbMultiplier.setItemText(1, QCoreApplication.translate("MainWindow", u"Brown", None))
        self.cbMultiplier.setItemText(2, QCoreApplication.translate("MainWindow", u"Red", None))
        self.cbMultiplier.setItemText(3, QCoreApplication.translate("MainWindow", u"Orange", None))
        self.cbMultiplier.setItemText(4, QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.cbMultiplier.setItemText(5, QCoreApplication.translate("MainWindow", u"Green", None))
        self.cbMultiplier.setItemText(6, QCoreApplication.translate("MainWindow", u"Blue", None))
        self.cbMultiplier.setItemText(7, QCoreApplication.translate("MainWindow", u"Violet", None))
        self.cbMultiplier.setItemText(8, QCoreApplication.translate("MainWindow", u"Gray", None))
        self.cbMultiplier.setItemText(9, QCoreApplication.translate("MainWindow", u"White", None))
        self.cbMultiplier.setItemText(10, QCoreApplication.translate("MainWindow", u"Gold", None))
        self.cbMultiplier.setItemText(11, QCoreApplication.translate("MainWindow", u"Silver", None))

        self.cbMultiplier.setProperty("placeholderText", QCoreApplication.translate("MainWindow", u"Multiplier", None))
        self.cbTolerance.setItemText(0, QCoreApplication.translate("MainWindow", u"Brown", None))
        self.cbTolerance.setItemText(1, QCoreApplication.translate("MainWindow", u"Red", None))
        self.cbTolerance.setItemText(2, QCoreApplication.translate("MainWindow", u"Orange", None))
        self.cbTolerance.setItemText(3, QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.cbTolerance.setItemText(4, QCoreApplication.translate("MainWindow", u"Gold", None))
        self.cbTolerance.setItemText(5, QCoreApplication.translate("MainWindow", u"Silver", None))
        self.cbTolerance.setItemText(6, QCoreApplication.translate("MainWindow", u"None", None))

        self.cbTolerance.setProperty("placeholderText", QCoreApplication.translate("MainWindow", u"Tolerance", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"D - Band", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Coded Value", None))
        self.lblCodedVal.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Tolerance Value", None))
        self.lblToleranceVal.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lblMaxTolerance.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Maximum:", None))
        self.lblMinTolerance.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Minimum:", None))
        self.btnSolve.setText(QCoreApplication.translate("MainWindow", u"SOLVE", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Multiplier", None))
        self.lblMultiplier.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Tolerance", None))
        self.lblTolerance.setText(QCoreApplication.translate("MainWindow", u"...", None))
    # retranslateUi

